import flet as ft

# Flet logo palette
FLET_PINK = "#EE3167"
FLET_BLUE = "#0098DA"
FLET_BLUE_LIGHT = "#5ABAE7"

# Dark theme colors (harmonized with Flet logo blues)
DARK_BG = "#1a1a2e"
DARK_SURFACE = "#1e2337"
DARK_CARD = "#252a3e"
DARK_HEADER = "#16213e"
DARK_TEXT = "#e0e0e0"
DARK_TEXT_SECONDARY = "#9e9e9e"
DARK_ACCENT = FLET_BLUE_LIGHT  # was #00bcd4, now matches logo
DARK_ACCENT_LIGHT = FLET_BLUE_LIGHT
DARK_DIVIDER = "#2d3250"
DARK_SEARCH_BG = "#2d3250"

# Light theme colors
LIGHT_BG = "#f5f5f5"
LIGHT_SURFACE = "#ffffff"
LIGHT_CARD = "#ffffff"
LIGHT_HEADER = FLET_BLUE
LIGHT_TEXT = "#212121"
LIGHT_TEXT_SECONDARY = "#757575"
LIGHT_ACCENT = FLET_BLUE
LIGHT_DIVIDER = "#e0e0e0"
LIGHT_SEARCH_BG = "#e8e8e8"

# Shared colors
STAR_COLOR = FLET_BLUE_LIGHT
DOWNLOAD_COLOR = FLET_BLUE_LIGHT
TAG_COLOR = FLET_BLUE_LIGHT
TAG_BG = "#1a3a4a"
SUCCESS_COLOR = "#4caf50"
ERROR_COLOR = "#f44336"

# Flet color references
PRIMARY_COLOR = ft.Colors.CYAN_400
SURFACE_COLOR = ft.Colors.SURFACE
